dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake
script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - gcc -v && g++ -v && cmake --version
  - g++ main.cpp assignment.cpp
